version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=moviepassword
      - POSTGRES_DB=Movie
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
