spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Movie
    username: movieuser
    password: moviepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:changelog/create_movie_table.yaml
    enabled: false

  application:
    name: demo

server:
  port: 8081